name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  ARTIFACT_PATH: artifacts
  #VERSION: "1.0.0-ci"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Environment
      run: env 
        
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: Setup 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build 
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test -c Release -r ${{ env.ARTIFACT_PATH }} --no-build -l trx --verbosity=normal
      
    - name: Pack
      run: dotnet pack -c Release -o ${{ env.ARTIFACT_PATH }} --no-build
      
    #- name: Publish 
    #  run: dotnet nuget push ${{ env.ARTIFACT_PATH }}/*.nupkg --api-key ${{ secrets.PUBLISH_PKG_KEY }} --source https://nuget.pkg.github.com/matthiasguentert/index.json
    
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ${{ env.ARTIFACT_PATH }}/**/*
        